graviton:
  owner: ktech-developer-platform
  env: test
  business: ktech
  schedule: "0 0 * * *"

  nodeStrategy:
    arch: arm64

spot:
  owner: ktech-developer-platform
  env: test
  business: ktech
  schedule: "0 0 * * *"

  nodeStrategy:
    capacityType: spot

spot-arm:
  owner: ktech-developer-platform
  env: test
  business: ktech
  schedule: "0 0 * * *"

  nodeStrategy:
    capacityType: spot
    arch: arm64
